### ISSUE TITLE
Problem running boolode

### ISSUE THREAD

**Issue by persa-alt** [Murali-group/BoolODE#19]
Goodmorning!!
I have a problem running the BoolODE. I tried the example which is in https://murali-group.github.io/Beeline/BoolODE.html#boolodeoptions but  when I run the config-files I always get this message:

(base) user@user-Inspiron-3671:~/Beeline/BoolODE$ python boolode.py --config ./config-files/example-comfig.yaml
Traceback (most recent call last):
  File "/home/user/Beeline/BoolODE/boolode.py", line 39, in <module>
    main()
  File "/home/user/Beeline/BoolODE/boolode.py", line 31, in main
    with open(config_file, 'r') as conf:
FileNotFoundError: [Errno 2] No such file or directory: './config-files/example-comfig.yaml'

Could you help me, please?

**Comment by amoghpj** [comment]
Hi, 
Thanks for using BoolODE!

Some comments:
1. Looks like there is a typo in your command, "comfig" -> "config" should fix the error. 
2. If you are trying to generate output for BEELINE, I recommend using the v0.1 release. This is available on the right panel on github under Release. The official documentation explains how to construct the command line arguments required for generating input datasets to BEELINE.

Happy to help with other issues.

**Comment by amoghpj** [comment]
Closing this for now. Feel free to reach out with any questions you might have.

**Comment by persa-alt** [comment]
Hi and thanks for your reply!!
Well,I downloaded the source code (tar.gz), extracted and saved it on my
desktop as BoolODE-0.1. Then I created a virtual environment and I
activated it.
Now, I' m trying to install requirements.txt but I' m encountering an
error.

(base) ***@***.***:~/Desktop/BoolODE-0.1$ python -m venv env
(base) ***@***.***:~/Desktop/BoolODE-0.1$ source
env/bin/activate
(env) (base) ***@***.***:~/Desktop/BoolODE-0.1$ pip install -r
requirements.txt
Collecting scipy==1.2.1 (from -r requirements.txt (line 1))
  Using cached scipy-1.2.1.tar.gz (23.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting matplotlib==3.0.3 (from -r requirements.txt (line 2))
  Using cached matplotlib-3.0.3-cp310-cp310-linux_x86_64.whl
Collecting numpy==1.16.2 (from -r requirements.txt (line 3))
  Using cached numpy-1.16.2.zip (5.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [155 lines of output]
      Running from numpy source directory.
      <string>:390: UserWarning: Unrecognized setuptools command,
proceeding with generating Cython sources and expanding templates

/tmp/pip-install-w5e4ks8v/numpy_748a3d078a264e509b8ebaff27d358a0/numpy/distutils/misc_util.py:476:
SyntaxWarning: "is" with a literal. Did you mean "=="?
        return is_string(s) and ('*' in s or '?' is s)
      blas_opt_info:
      blas_mkl_info:
      customize UnixCCompiler
        libraries mkl_rt not found in
['/home/user/Desktop/BoolODE-0.1/env/lib', '/usr/local/lib', '/usr/lib',
'/usr/lib/x86_64-linux-gnu']
        NOT AVAILABLE

      blis_info:
      customize UnixCCompiler
        libraries blis not found in
['/home/user/Desktop/BoolODE-0.1/env/lib', '/usr/local/lib', '/usr/lib',
'/usr/lib/x86_64-linux-gnu']
        NOT AVAILABLE

      openblas_info:
      customize UnixCCompiler
      customize UnixCCompiler
        libraries openblas not found in
['/home/user/Desktop/BoolODE-0.1/env/lib', '/usr/local/lib', '/usr/lib',
'/usr/lib/x86_64-linux-gnu']
        NOT AVAILABLE

      atlas_3_10_blas_threads_info:
      Setting PTATLAS=ATLAS
      customize UnixCCompiler
        libraries tatlas not found in
['/home/user/Desktop/BoolODE-0.1/env/lib', '/usr/local/lib', '/usr/lib',
'/usr/lib/x86_64-linux-gnu']
        NOT AVAILABLE

      atlas_3_10_blas_info:
      customize UnixCCompiler
        libraries satlas not found in
['/home/user/Desktop/BoolODE-0.1/env/lib', '/usr/local/lib', '/usr/lib',
'/usr/lib/x86_64-linux-gnu']
        NOT AVAILABLE

      atlas_blas_threads_info:
      Setting PTATLAS=ATLAS
      customize UnixCCompiler
        libraries ptf77blas,ptcblas,atlas not found in
['/home/user/Desktop/BoolODE-0.1/env/lib', '/usr/local/lib', '/usr/lib',
'/usr/lib/x86_64-linux-gnu']
        NOT AVAILABLE

      atlas_blas_info:
      customize UnixCCompiler
        libraries f77blas,cblas,atlas not found in
['/home/user/Desktop/BoolODE-0.1/env/lib', '/usr/local/lib', '/usr/lib',
'/usr/lib/x86_64-linux-gnu']
        NOT AVAILABLE

      accelerate_info:
        NOT AVAILABLE


/tmp/pip-install-w5e4ks8v/numpy_748a3d078a264e509b8ebaff27d358a0/numpy/distutils/system_info.py:638:
UserWarning:
          Atlas (http://math-atlas.sourceforge.net/) libraries not found.
          Directories to search for the libraries can be specified in the
          numpy/distutils/site.cfg file (section [atlas]) or by setting
          the ATLAS environment variable.
        self.calc_info()
      blas_info:
      customize UnixCCompiler
      customize UnixCCompiler
      C compiler: gcc -pthread -B /home/user/anaconda3/compiler_compat
-Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2
-isystem /home/user/anaconda3/include -fPIC -O2 -isystem
/home/user/anaconda3/include -fPIC

      creating /tmp/tmpdm00mybr/tmp
      creating /tmp/tmpdm00mybr/tmp/tmpdm00mybr
      compile options: '-I/usr/local/include -I/usr/include
-I/home/user/Desktop/BoolODE-0.1/env/include -c'
      gcc: /tmp/tmpdm00mybr/source.c
      gcc -pthread -B /home/user/anaconda3/compiler_compat
/tmp/tmpdm00mybr/tmp/tmpdm00mybr/source.o -L/usr/lib/x86_64-linux-gnu
-lcblas -o /tmp/tmpdm00mybr/a.out
      /home/user/anaconda3/compiler_compat/ld: cannot find -lcblas: No such
file or directory
      collect2: error: ld returned 1 exit status
      gcc -pthread -B /home/user/anaconda3/compiler_compat
/tmp/tmpdm00mybr/tmp/tmpdm00mybr/source.o -L/usr/lib/x86_64-linux-gnu
-lblas -o /tmp/tmpdm00mybr/a.out
      /home/user/anaconda3/compiler_compat/ld: warning: libm.so.6, needed
by /usr/lib/x86_64-linux-gnu/libblas.so, not found (try using -rpath or
-rpath-link)
      /home/user/anaconda3/compiler_compat/ld:
/usr/lib/x86_64-linux-gnu/libblas.so: undefined reference to
***@***.***_2.2.5'
      /home/user/anaconda3/compiler_compat/ld:
/usr/lib/x86_64-linux-gnu/libblas.so: undefined reference to
***@***.***_2.2.5'
      collect2: error: ld returned 1 exit status
      Traceback (most recent call last):
        File
"/tmp/pip-build-env-rgauc4mu/overlay/lib/python3.10/site-packages/setuptools/_distutils/unixccompiler.py",
line 266, in link
          self.spawn(linker + ld_args)
        File
"/tmp/pip-install-w5e4ks8v/numpy_748a3d078a264e509b8ebaff27d358a0/numpy/distutils/ccompiler.py",
line 92, in <lambda>
          m = lambda self, *args, **kw: func(self, *args, **kw)
        File
"/tmp/pip-install-w5e4ks8v/numpy_748a3d078a264e509b8ebaff27d358a0/numpy/distutils/ccompiler.py",
line 171, in CCompiler_spawn
          raise DistutilsExecError('Command "%s" failed with exit status
%d%s' %
      distutils.errors.DistutilsExecError: Command "gcc -pthread -B
/home/user/anaconda3/compiler_compat
/tmp/tmpdm00mybr/tmp/tmpdm00mybr/source.o -L/usr/lib/x86_64-linux-gnu
-lcblas -o /tmp/tmpdm00mybr/a.out" failed with exit status 1

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File
"/tmp/pip-install-w5e4ks8v/numpy_748a3d078a264e509b8ebaff27d358a0/numpy/distutils/system_info.py",
line 1733, in has_cblas
          c.link_executable(obj, os.path.join(tmpdir, "a.out"),
        File
"/tmp/pip-build-env-rgauc4mu/overlay/lib/python3.10/site-packages/setuptools/_distutils/ccompiler.py",
line 781, in link_executable
          self.link(
        File
"/tmp/pip-build-env-rgauc4mu/overlay/lib/python3.10/site-packages/setuptools/_distutils/unixccompiler.py",
line 268, in link
          raise LinkError(msg)
      distutils.errors.LinkError: Command "gcc -pthread -B
/home/user/anaconda3/compiler_compat
/tmp/tmpdm00mybr/tmp/tmpdm00mybr/source.o -L/usr/lib/x86_64-linux-gnu
-lcblas -o /tmp/tmpdm00mybr/a.out" failed with exit status 1

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File
"/tmp/pip-build-env-rgauc4mu/overlay/lib/python3.10/site-packages/setuptools/_distutils/unixccompiler.py",
line 266, in link
          self.spawn(linker + ld_args)
        File
"/tmp/pip-install-w5e4ks8v/numpy_748a3d078a264e509b8ebaff27d358a0/numpy/distutils/ccompiler.py",
line 92, in <lambda>
          m = lambda self, *args, **kw: func(self, *args, **kw)
        File
"/tmp/pip-install-w5e4ks8v/numpy_748a3d078a264e509b8ebaff27d358a0/numpy/distutils/ccompiler.py",
line 171, in CCompiler_spawn
          raise DistutilsExecError('Command "%s" failed with exit status
%d%s' %
      distutils.errors.DistutilsExecError: Command "gcc -pthread -B
/home/user/anaconda3/compiler_compat
/tmp/tmpdm00mybr/tmp/tmpdm00mybr/source.o -L/usr/lib/x86_64-linux-gnu
-lblas -o /tmp/tmpdm00mybr/a.out" failed with exit status 1

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File
"/home/user/Desktop/BoolODE-0.1/env/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py",
line 353, in <module>
          main()
        File
"/home/user/Desktop/BoolODE-0.1/env/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py",
line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File
"/home/user/Desktop/BoolODE-0.1/env/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py",
line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File
"/tmp/pip-build-env-rgauc4mu/overlay/lib/python3.10/site-packages/setuptools/build_meta.py",
line 380, in prepare_metadata_for_build_wheel
          self.run_setup()
        File
"/tmp/pip-build-env-rgauc4mu/overlay/lib/python3.10/site-packages/setuptools/build_meta.py",
line 487, in run_setup
          super(_BuildMetaLegacyBackend,
        File
"/tmp/pip-build-env-rgauc4mu/overlay/lib/python3.10/site-packages/setuptools/build_meta.py",
line 338, in run_setup
          exec(code, locals())
        File "<string>", line 415, in <module>
        File "<string>", line 407, in setup_package
        File
"/tmp/pip-install-w5e4ks8v/numpy_748a3d078a264e509b8ebaff27d358a0/numpy/distutils/core.py",
line 137, in setup
          config = configuration()
        File "<string>", line 164, in configuration
        File
"/tmp/pip-install-w5e4ks8v/numpy_748a3d078a264e509b8ebaff27d358a0/numpy/distutils/misc_util.py",
line 1034, in add_subpackage
          config_list = self.get_subpackage(subpackage_name,
subpackage_path,
        File
"/tmp/pip-install-w5e4ks8v/numpy_748a3d078a264e509b8ebaff27d358a0/numpy/distutils/misc_util.py",
line 1000, in get_subpackage
          config = self._get_configuration_from_setup_py(
        File
"/tmp/pip-install-w5e4ks8v/numpy_748a3d078a264e509b8ebaff27d358a0/numpy/distutils/misc_util.py",
line 942, in _get_configuration_from_setup_py
          config = setup_module.configuration(*args)
        File "numpy/setup.py", line 10, in configuration
          config.add_subpackage('core')
        File
"/tmp/pip-install-w5e4ks8v/numpy_748a3d078a264e509b8ebaff27d358a0/numpy/distutils/misc_util.py",
line 1034, in add_subpackage
          config_list = self.get_subpackage(subpackage_name,
subpackage_path,
        File
"/tmp/pip-install-w5e4ks8v/numpy_748a3d078a264e509b8ebaff27d358a0/numpy/distutils/misc_util.py",
line 1000, in get_subpackage
          config = self._get_configuration_from_setup_py(
        File
"/tmp/pip-install-w5e4ks8v/numpy_748a3d078a264e509b8ebaff27d358a0/numpy/distutils/misc_util.py",
line 942, in _get_configuration_from_setup_py
          config = setup_module.configuration(*args)
        File "numpy/core/setup.py", line 758, in configuration
          blas_info = get_info('blas_opt', 0)
        File
"/tmp/pip-install-w5e4ks8v/numpy_748a3d078a264e509b8ebaff27d358a0/numpy/distutils/system_info.py",
line 445, in get_info
          return cl().get_info(notfound_action)
        File
"/tmp/pip-install-w5e4ks8v/numpy_748a3d078a264e509b8ebaff27d358a0/numpy/distutils/system_info.py",
line 638, in get_info
          self.calc_info()
        File
"/tmp/pip-install-w5e4ks8v/numpy_748a3d078a264e509b8ebaff27d358a0/numpy/distutils/system_info.py",
line 1663, in calc_info
          blas_info = get_info('blas')
        File
"/tmp/pip-install-w5e4ks8v/numpy_748a3d078a264e509b8ebaff27d358a0/numpy/distutils/system_info.py",
line 445, in get_info
          return cl().get_info(notfound_action)
        File
"/tmp/pip-install-w5e4ks8v/numpy_748a3d078a264e509b8ebaff27d358a0/numpy/distutils/system_info.py",
line 638, in get_info
          self.calc_info()
        File
"/tmp/pip-install-w5e4ks8v/numpy_748a3d078a264e509b8ebaff27d358a0/numpy/distutils/system_info.py",
line 1699, in calc_info
          lib = self.has_cblas(info)
        File
"/tmp/pip-install-w5e4ks8v/numpy_748a3d078a264e509b8ebaff27d358a0/numpy/distutils/system_info.py",
line 1739, in has_cblas
          c.link_executable(obj, os.path.join(tmpdir, "a.out"),
        File
"/tmp/pip-build-env-rgauc4mu/overlay/lib/python3.10/site-packages/setuptools/_distutils/ccompiler.py",
line 781, in link_executable
          self.link(
        File
"/tmp/pip-build-env-rgauc4mu/overlay/lib/python3.10/site-packages/setuptools/_distutils/unixccompiler.py",
line 268, in link
          raise LinkError(msg)
      distutils.errors.LinkError: Command "gcc -pthread -B
/home/user/anaconda3/compiler_compat
/tmp/tmpdm00mybr/tmp/tmpdm00mybr/source.o -L/usr/lib/x86_64-linux-gnu
-lblas -o /tmp/tmpdm00mybr/a.out" failed with exit status 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a
problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.





Στις Τρί 25 Απρ 2023 στις 2:51 μ.μ., ο/η Amogh Jalihal <
***@***.***> έγραψε:

**Comment by amoghpj** [comment]
Apologies for the late response. The errors look like problems with setting up the virtual environment. The `requirements.txt` lists some soft dependencies, but we are not using any functions that are tied to those library versions. That means that simply installing the latest versions of scikit-learn, matplotlib, numpy, and pandas should be sufficient for BoolODE. Hope this helps.
